name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g surge
      - run: npm install
      - run: npm run build
      - run: mv build/index.html build/200.html
      - run: surge ./build --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}